name: Generate Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Side-by-Side Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_STATS_TOKEN }}
          user: stellaappiok
          template: repository
          # This pulls in the Stats (left side)
          base: header, activity, community, repositories, metadata
          
          # This enables the Languages panel (right side)
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          
          # This puts them side-by-side
          config_padding: 0, 8 + 11%
          config_display: columns
