name: Generate Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Languages Stats
        uses: lowlighter/metrics@latest
        with:
          filename: github-languages.svg
          token: ${{ secrets.METRICS_STATS_TOKEN }} # Updated token name here
          user: YOUR_USERNAME_HERE
          base: "" 
          template: classic
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          plugin_languages_limit: 10

      - name: Generate Base Stats
        uses: lowlighter/metrics@latest
        with:
          filename: github-stats.svg
          token: ${{ secrets.METRICS_STATS_TOKEN }} # Updated token name here
          user: YOUR_USERNAME_HERE
          template: classic
          base: header, activity, community, repositories, metadata
          plugin_lines: yes
